/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 *
 //*
 * main.c
 *
 * Description:
 * This project follows a modular programming approach.
 * UART functionality is implemented in uart.c / uart.h.
 * ADC with DMA functionality is implemented in adc_dma.c / adc_dma.h.
 *
 * main.c contains the application control logic and
 * integrates all peripheral modules.
 */

#include<stdint.h>
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif
#include "uart.h"
#include "adc_dma.h"

int main(void)
{
    uart_init();
    adc_dma_init();

    while (1)
    {
        uart_send_dec(adc_buffer[0]);
        uart_send_string("\r\n");

        for (volatile int d = 0; d < 200000; d++);  // small readable delay
    }
}

